name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]  # 监听 main 分支的推送

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1. 拉取代码
      - uses: actions/checkout@v4

      # 2. （可选）构建步骤示例
      - name: Setup files
        run: |
          echo "构建时间: $(date)" > version.txt
          chmod -R 755 *.html *.js  # 修复权限

      # 3. 部署到 GitHub Pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./            # 部署根目录下的所有文件
          keep_files: false          # 清理旧文件
          enable_jekyll: false       # 禁用 Jekyll 处理
