name: Deploy Anti-Redirect System

on:
  push:
    branches: [ "main" ]  # 监听main分支的推送
  workflow_dispatch:      # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5    # 防止卡死

    steps:
      # 1. 拉取代码
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史

      # 2. 设置部署目录
      - name: Prepare Files
        run: |
          mkdir -p public
          cp -R src/* public/  # 复制src所有内容到public
          echo "Deployed at $(date)" > public/deploy.txt  # 生成部署标记

      # 3. 自动修复文件权限（防止403错误）
      - name: Fix Permissions
        run: |
          find public -type f -exec chmod 644 {} \;
          find public -type d -exec chmod 755 {} \;

      # 4. 部署到GitHub Pages
      - uses: peaceiris/actions-gh-pages@v3
        id: deployment  # 用于后续步骤引用
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: false  # 每次清理旧文件
          force_orphan: true  # 强制纯净部署
          enable_jekyll: false # 禁用Jekyll处理

      # 5. 验证部署结果
      - name: Verify Deployment
        run: |
          DEPLOY_URL="https://${{ github.repository_owner }}.github.io/${{ github.repository }}/"
          echo "Deployed to: $DEPLOY_URL"
          curl -sI "$DEPLOY_URL" | grep -q "200 OK" || (echo "Deployment failed!"; exit 1)
